// Generated by graph2asy.
// Python Script written by Supakorn "Jamie" R. :)
// Created at 2018-09-27 13:45:34.172842

// header
size(6cm);

// options
real circrad= 0.15 ;
// edges
// processing edge (0, 1, {'label': '$4$', 'align': 'N'})
path edge_1=(0, 0)--(1, 0);
draw((edge_1),arrow=Arrow(Relative(1.0 - circrad/arclength(edge_1))));
label("$4$",edge_1,align=N);

// processing edge (0, 4, {'label': '$7$', 'align': 'NW'})
path edge_2=(0, 0)--(1, 1);
draw((edge_2),arrow=Arrow(Relative(1.0 - circrad/arclength(edge_2))));
label("$7$",edge_2,align=NW);

// processing edge (1, 2, {'label': '$7$', 'align': 'N'})
path edge_3=(1, 0)--(2, 0);
draw((edge_3),arrow=Arrow(Relative(1.0 - circrad/arclength(edge_3))));
label("$7$",edge_3,align=N);

// processing edge (1, 5, {'label': '$2$', 'align': 'SW'})
path edge_4=(1, 0)--(2, -1);
draw((edge_4),arrow=Arrow(Relative(1.0 - circrad/arclength(edge_4))));
label("$2$",edge_4,align=SW);

// processing edge (2, 3, {'label': '$4$', 'align': 'N'})
path edge_5=(2, 0)--(3, 0);
draw((edge_5),arrow=Arrow(Relative(1.0 - circrad/arclength(edge_5))));
label("$4$",edge_5,align=N);

// processing edge (4, 2, {'label': '$5$', 'align': 'NE'})
path edge_6=(1, 1)--(2, 0);
draw((edge_6),arrow=Arrow(Relative(1.0 - circrad/arclength(edge_6))));
label("$5$",edge_6,align=NE);

// processing edge (5, 3, {'label': '$3$', 'align': 'SE'})
path edge_7=(2, -1)--(3, 0);
draw((edge_7),arrow=Arrow(Relative(1.0 - circrad/arclength(edge_7))));
label("$3$",edge_7,align=SE);


// vertices
// processing node id 0
unfill(circle((0, 0),circrad));
draw(circle((0, 0),circrad));
label("s", (0, 0));

// processing node id 1
unfill(circle((1, 0),circrad));
draw(circle((1, 0),circrad));
label("b", (1, 0));

// processing node id 2
unfill(circle((2, 0),circrad));
draw(circle((2, 0),circrad));
label("c", (2, 0));

// processing node id 3
unfill(circle((3, 0),circrad));
draw(circle((3, 0),circrad));
label("t", (3, 0));

// processing node id 4
unfill(circle((1, 1),circrad));
draw(circle((1, 1),circrad));
label("a", (1, 1));

// processing node id 5
unfill(circle((2, -1),circrad));
draw(circle((2, -1),circrad));
label("d", (2, -1));

